[package]
name = "oxylisp"
version = "0.1.0"
authors = ["Grégoire de Massé <demasse.gregoire@yahoo.fr>"]
edition = "2018"

[dependencies]

[lib]
name = "oxylisp"
path = "src/lib.rs"

[[bin]]
name = "oxylisp"
path = "src/main.rs"